### ISSUE TITLE
Code from tutorial 5 not working

### ISSUE THREAD

**Issue by pranav-singhal** [willitscale/learning-solidity#11]
I tried running the code from tutorial 5 on remix.etherum.org
 and I get the following error

        VM error: revert.
        revert	The transaction has been reverted to the initial state.
        Note: The constructor should be payable if you send value.	Debug the transaction to get 
        more information.

**Comment by difengJ** [comment]
what is your value. does it above 1 ether?

**Comment by pranav-singhal** [comment]
yes

**Comment by FloryanFilip** [comment]
You are probably trying to DEPLOY the contract with some ether, which won't work since the contructor isn't payable.

You should deploy your contract without any ether specified and then call the 'fallback' function with ether 'inserted'

**Comment by willitscale** [comment]
Closing as you must deploy the contract with no Ether as @FloryanFilip stated:

> You are probably trying to DEPLOY the contract with some ether, which won't work since the contructor isn't payable.
> 
> You should deploy your contract without any ether specified and then call the 'fallback' function with ether 'inserted'
