### ISSUE TITLE
tutorial-01 issue

### ISSUE THREAD

**Issue by nikogamulin** [willitscale/learning-solidity#14]
I tried to run the contract but was unable to get name and age by calling functions getName() and getAge(). Then I modified get functions the following way and it works fine:

```
function getName() public view returns (string) {
        return name;
    }
```

```
function getAge() public view returns (uint) {
        return age;
    }
```

**Comment by ramakrishnaBLR** [comment]
what is the actula code before modified get functions..?

**Comment by willitscale** [comment]
I resolved this here https://github.com/willitscale/learning-solidity/pull/22 they're just lint warnings, but should still work.
