### ISSUE TITLE
Documenting Smart Contracts

### ISSUE THREAD

**Issue by balajipachai** [willitscale/learning-solidity#39]
Hi,

The repo seems great. The initiative to lead in teaching solidity fantastic. Smart contracts well developed.
I noticed that the smart contracts are not documented or say well commented, also the require statements are missing reason strings.

I am interested in taking this up and adding all the required missing parts.
Waiting for a go-ahead from the maintainers.

Thanks,
Balaji

**Comment by willitscale** [comment]
Hey Balaji,

Sorry, I'm not a fan of commenting code for the two principals of code should be written without comments and inline comments are typically only relative to only the commentator. The supporting videos should cover what the code is doing and the documentation should provide the rest.

Thanks,
James

**Comment by balajipachai** [comment]
Got it, closing the same.
